spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:market
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
